version: '3.7'

services:
  backend:
    build: ./backendAPI
    container_name: backend
    networks:
      - app-network
    depends_on:
      - database

  database:
    build: ./database
    container_name: database
    networks:
      - app-network

  httpd:
    build: ./httpServer
    container_name: httpd
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
